version: 2
defaults: &defaults
  working_directory: /tmp/ddnet
  docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init

jobs:
  pre_test:
    steps:
      - checkout
      - run: python scripts/check_header_guards.py

  build:
    parallelism: 1
    #environment:
      #CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      #CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
    steps:
      - checkout
      #- run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: git submodule update --init
      - run: |
          sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
          sudo apt-get update
          sudo apt-get build-dep teeworlds
          sudo apt-get install cmake libsdl2-dev xz-utils

      # Compile
      - run: python scripts/check_header_guards.py
      - run: |
          mkdir build
          cd build
          env CFLAGS="-Wdeclaration-after-statement -Werror" CXXFLAGS="-Werror" cmake -DDOWNLOAD_GTEST=ON ..
          make everything

      - persist-to-workspace:
        root: build
        paths:
          - *

  test:
    steps:
      - attach-workspace:
        at: build/

      - run: |
          cd build
          make run_tests
          ./DDNet-Server shutdown

workflows:
    version: 2
    build_and_test:
        jobs:
            - pre_test
            - build:
                requires:
                    - pre_test
            - test:
                requires:
                    - build
